### ISSUE TITLE
Possible to define multiple testserver?

### ISSUE THREAD

**Issue by kellcomnet2** [ansemjo/speedtest-plotter#61]
My isp want me to use 3 different test servers to show the problem isn’t with one test destination. Is it possible to define multiple test servers? Ideally they would be run sequentially and each have their own separate plot lines.

**Comment by ansemjo** [comment]
No, there is currently none and I would not want to add more plot lines to the graph either, to be honest.

* Easiest right now would be to simply start three separate containers with slightly different cron schedules. That will give you one plot per testserver.
* Otherwise, you could start only one and use a script inside the container, which iterates through a list and calls `speedtest-plotter measure -s <server>`. Be sure to remove or replace the cron job in `/var/spool/cron/crontabs/root` in that case, so you don't accidentally start two measurements in parallel.

```ash
#!/usr/bin/env ash

while true; do
  for server in <testserver1> <testserver2> ...; do
    speedtest-plotter -s $server measure
  done
  sleep 600
done
```

**Comment by ansemjo** [comment]
@kellcomnet2 is that a viable solution for you?

**Comment by kellcomnet2** [comment]
The separate containers approach didn’t work for me as I ran into timing issues I am playing around with a couple of other options but I am good to close this as the main intention was to verify if there was a way to do it “out of box” I don’t expect you to code for every situation.

**Comment by ansemjo** [comment]
Great. Thank you for understanding. :)

> [...] I ran into timing issues

I guess that's because all the containers tried to run with the same cron schedule? You can define those explicitly with `docker run ... -e SCHEDULE="<cron schedule>" ...`. For example, three containers with schedules shifted by 5 minutes might be started with:

```
docker run ... -e SCHEDULE="0,15,30,45 * * * *" ghcr.io/ansemjo/speedtest
docker run ... -e SCHEDULE="5,20,35,50 * * * *" ghcr.io/ansemjo/speedtest
docker run ... -e SCHEDULE="10,25,40,50 * * * *" ghcr.io/ansemjo/speedtest

**Comment by kellcomnet2** [comment]
It “worked” but issue was trying to minimize gap between the speed tests as speedtest to the provider never has an issue but external access speeds would dropout for a minute or several at a time. If the issue resolved between when one ended and the next test began it appeared that the issue was with one particular test server. Intermittent issues with short intervals are a pain in the butt to troubleshoot.
