### ISSUE TITLE
Release Note and Changelog

### ISSUE THREAD

**Issue by corasaniti** [ansemjo/speedtest-plotter#85]
Hi

it would be nice for every release or push to dockehub, to write a release note or changelog to know the improvements and changes.
Thanks

**Comment by ansemjo** [comment]
Hi, thanks for the suggestion!

1. In general, I am in the process of moving away from DockerHub. The `ansemjo/speedtest` image is the last one that I still push on my DockerHub account. My GitHub action workflows mostly push to GitHub's own container registry ghcr.io now: [`ghcr.io/ansemjo/speedtest`](https://github.com/ansemjo/speedtest-plotter/pkgs/container/speedtest)
2. I remember that when we created the GitHub workflows, there was an issue that you could not update an image's description using token authentication. I dug around and apparently the issue still exists today: https://github.com/docker/hub-tool/issues/172

Therefore, as a compromise, would maintaining a `CHANGELOG.md` in-repo and linking to it from the Readme and image description on DockerHub be adequate? For most of the things that `dependabot` updates through its pull-requests, I don't even bother to bump the minor version because those updates shouldn't change any functionality. Was there something that broke you you recently?

**Comment by corasaniti** [comment]
Could you write the released version on the web page with the graphic? Thanks

**Comment by ansemjo** [comment]
I've started a [changelog](CHANGELOG.md) and the DockerHub description now points to the README and CHANGELOG files in this repository. I won't update the image description on DockerHub for every new release.

The latest tagged release can be found under [Releases on GitHub](https://github.com/ansemjo/speedtest-plotter/tags) or in the list of [package versions](https://github.com/ansemjo/speedtest-plotter/pkgs/container/speedtest/versions), since the images released to ghcr.io will always be the same as those pushed to DockerHub.
