### ISSUE TITLE
Error when starting measurement

### ISSUE THREAD

**Issue by Fischy667** [ansemjo/speedtest-plotter#93]
When a measurement is started I get the following error and no measurement is running: 

`Error relocating /usr/local/bin/SpeedTest: _ZSt28__throw_bad_array_new_lengthv: symbol not found`

It makes no difference if the measurement is started via scheduler or manually.

**Comment by ansemjo** [comment]
The only change that happened between `ghcr.io/ansemjo/speedtest@sha256:c238add0caebbd72f61e3421ff4e6e8c705682110fbb20c825a3672fe8f2d95e` (yesterday's `latest`) and today is the bump to Alpine 3.16.0 ...

- [ ] revert to Alpine 3.15.* for now
- [ ] add a CI stage that attempts to run a measurement in the built container

**Comment by ansemjo** [comment]
Alright, I [amended the workflow to run a test measurement with the built image](https://github.com/ansemjo/speedtest-plotter/commit/5e550573478bf852cc188394faaf3f2550224a4e). It [correctly caught this issue](https://github.com/ansemjo/speedtest-plotter/runs/6582093651?check_suite_focus=true) when bumping `devel` back to Alpine 3.16.

I'm still not sure what the actual issue is; it looks like some build dependencies have mixed in versions from `edge`. I think I'll just stay on Alpine 3.15 for now.
